dist: xenial  # required for Python >= 3.7
language: python

cache: pip

python:
  - "3.7"

os: linux

sudo: required

git:
  depth: 1

before_install:
  # Setup conda (needed for opencv, ray dependency)
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export TEST_FLAG="True"

  # clone softlearning library
  - git clone https://github.com/rail-berkeley/softlearning.git ~/softlearning

  # necessary for pyglet renderer
  - export DISPLAY=:0.0

  # Set up requirements for flow
  - conda env create -f environment.yml
  - source activate flow

  # [sumo] dependencies and binaries
  - pushd $HOME/build/flow-project
  -     ./flow/scripts/setup_sumo_ubuntu1604.sh
  - popd
  - source ~/.bashrc

  # [aimsun] install the conda env and update the path to the env
  - pushd $HOME/build/flow-project
  -     ./flow/scripts/setup_aimsun.sh
  - popd
  - source ~/.bashrc
  - sed -i 's/\/path\/to\/envs\/aimsun_flow/\/home\/travis\/miniconda\/envs\/aimsun_flow/g' flow/config.py

  - ls ../

install:
  - pip install flake8 .
  - pip install coveralls
  - pip install nose
  - pip install matplotlib
  - pip install jupyter
  - conda install -y patchelf=0.9
  - pip install tensorflow-probability
  - pip install gtimer
  - pip install -U ray
  - pip install -U pyglet
  - pip install git+https://github.com/hartikainen/serializable.git
  - pip install flatten-dict
  - pip install -e ~/softlearning

before_script:
  - flake8 --version
  - flake8 --show-source

script:
  - python setup.py install
  - nose2 --with-coverage

after_success:
  - coveralls
